spring.application.name=just-10-minutes

#Datasource
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/localDB?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.username=root
spring.datasource.hikari.password=1q2w3e4r
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10

mybatis.configuration.map-underscore-to-camel-case=true

#iamport
payment.iamport.url=https://api.iamport.kr
payment.iamport.api_key=1467178214104648
payment.iamport.api_secret=M11mpNrYutDR7gnIv8Sg6bPJ3IIoLSnKs49Z80SZxdPJoNSgQUUIjFuVB2MAKU69zPpfP0kyCODCtLRf
payment.iamport.nice_pg=nice_v2.iamport01m

#prometheus
management.endpoints.web.exposure.include=prometheus
