spring:
  application:
    name: "just-10-minutes"
  datasource:
    url: ${DB_URL}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sqs:
        queue-name:
          notification-event-fifo: Notification.fifo

mybatis:
  configuration:
    map-underscore-to-camel-case: true

payment:
  iamport:
    url: ${IAMPORT_URL}
    api_key: ${IAMPORT_KEY}
    api_secret: ${IAMPORT_SECRETE}
    nice_pg: "nice_v2.iamport01m"
  test:
    card_number: ${CARD_NUMBER}
    card_expiry: ${CARD_EXPIRY}
    card_birth: ${CARD_BIRTH}
    card_pwd2digit: ${CARD_PWD2DIGIT}

message:
  fcm:
    base_url: ${FCM_API_BASE_URL}
    message_postfix: ${FCM_API_MESSAGE_POSTFIX}
    credential_url: ${FCM_GOOGLE_API_CREDENTIAL_URL}
    key_path: ${FCM_KEY_PATH}

#prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus

webhook:
  slack:
    url: ${SLACK_WEBHOOK_URL}