spring:
application:
name: "just-10-minutes"
#Datasource
datasource:
hikari:
jdbc-url: "jdbc:mysql://localhost:3306/localDB?serverTimezone=UTC&characterEncoding=UTF-8"
driver-class-name: "com.mysql.cj.jdbc.Driver"
username: "root"
password: "1q2w3e4r"

#Mybatis
mybatis:
configuration:
map-underscore-to-camel-case: true

#iamport
payment:
iamport:
url: "https://api.iamport.kr"
api_key: "1467178214104648"
api_secret: "M11mpNrYutDR7gnIv8Sg6bPJ3IIoLSnKs49Z80SZxdPJoNSgQUUIjFuVB2MAKU69zPpfP0kyCODCtLRf"
nice_pg: "nice_v2.iamport01m"

#prometheus
management:
endpoints:
web:
exposure:
include: "prometheus"
